### ISSUE TITLE
Png file format nonsupport in the new macOS high sierra, only use icns 

### ISSUE THREAD

**Issue by ghost** [una/gradient-folders#1]
System: macOS 10.13.2 high sierra

**Comment by rifaidev** [comment]
You can use this [Image2Icon](http://www.img2icnsapp.com/) app to convert `.PNG` to `.ICNS` or simply drag the image to Image2Icon, then drag your folder to apply it.

**Comment by joshvickerson** [comment]
The article @una [links to in the readme](https://www.hongkiat.com/blog/customize-mac-folder-icon/) notes that you need to open the file in Preview before copying / pasting. Give that a shot?

**Comment by Blackbaud-BobbyEarl** [comment]
I was experiencing the same problem on High Sierra.  The workaround @joshvickerson mentioned did work for me.

**Comment by una** [comment]
Open the image in preview, then copy and paste it into the folder icon. Let me know if this works @bondBo! I'm also on High Sierra :)

**Comment by ozturkcangokkaya** [comment]
@una Opening the image in preview works. Thank you :)
